### ISSUE TITLE
Add a conversion rate between BNB and BUSD to new job creation form

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#21]
We would like to have a possibility to let customers know about actual conversion rate in `NewJobForm` component.

Now customers are able to use BNB in the form and they don't know about actual price of USD.

How this form looks like:
<img width="1162" alt="Screenshot 2023-02-14 at 1 59 18 AM" src="https://user-images.githubusercontent.com/335095/218584228-9698db23-69c4-42b6-bc9f-741ed74b9310.png">

How this conversion can be implemented:
1. When customer opens a new job form, we make a request (using browser request) to [https://api.binance.com/api/v3/avgPrice?symbol=BNBBUSD](https://api.binance.com/api/v3/avgPrice?symbol=BNBBUSD) (no API keys needed) and store the `price` field in a variable
2. Maybe it would be good to replace direct API request to Binance into Next.js internal API route and implement caching mechanism?
3. When customer changes the "budget" field in the form, we automatically convert this value into USD and display it somewhere in this form, maybe close to "budget" field, like in [this example](https://react.semantic-ui.com/elements/input/#variations-right-labeled-basic)

When this feature will be implemented, then we use the same pattern in `ApplicationForm` and `NewContractForm` but in different PRs.

**Comment by sergiimyk** [comment]
For how long should we cache the result? I don't have any suggestion here, have no idea what could work better, since the price is changing any moment, but the change is not that big. Maybe 5-10min?

**Comment by gruz0** [comment]
Done.
