### ISSUE TITLE
Add suggestion to NewJobForm to let customer know how to minimize gas fees

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#34]
It would be great to let customers know how to minimize cost of gas fees while creating a new task on the platform.

We can mention, that customers may attach links to Google Docs or GitHub (using our Markdown markup, for example) with detailed explanation of their tasks and minimize transaction fees.

**Please provide your ideas about this task before implementing this feature.**

Reference: https://github.com/optriment/optrispace-frontend-v2/blob/master/src/forms/NewJobForm/index.jsx#L358

**Comment by sergiimyk** [comment]
#43
