### ISSUE TITLE
Bored Information table copy error

### ISSUE THREAD

**Issue by sergiimyk** [optriment/optrispace-frontend-v2#38]
In the boring information table, number 3. is wrong in the freelancer screen. It refers that the freelancer is responsible for funding the contract, while it should be "Customer"
![2023-02-20_00-28](https://user-images.githubusercontent.com/25285245/219985018-036adb08-1651-4aee-956d-88ac2fd0eca1.png)

**Comment by gruz0** [comment]
Great! Also we have to change "Bored Information" to something useful. Maybe "Extra Details"? WDYT?

**Comment by sergiimyk** [comment]
Extra details looks good to me. Some other suggestions: Additional information, supplementary details, more specifics, detailed view, etc

**Comment by gruz0** [comment]
> Extra details looks good to me. Some other suggestions: Additional information, supplementary details, more specifics, detailed view, etc

Detailed View :+1:

**Comment by Aditya-A-G** [comment]
hey, I would like to work on this issue!
