### ISSUE TITLE
Exclude jobs older than 30 days from /jobs listing

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#55]
We don't have mechanism to hide outdated jobs on blockchain side, so we need to implement this feature on a frontend first. And when we will be ready to replace an existing function `gigsGetJobs` in smart contracts, then we can remove this functionality from frontend.

How it should be implemented:

1. We have [jobs/index screen](https://github.com/optriment/optrispace-frontend-v2/blob/master/src/screens/jobs/index/index.jsx#L35)
2. Add filter to items to exclude all with `createdAt` attribute older than 30 days

**Comment by Aditya-A-G** [comment]
hey @gruz0, i would like to work on this issue

**Comment by gruz0** [comment]
> hey @gruz0, i would like to work on this issue

Hi! This task is in progress already (@sergiimyk)
