### ISSUE TITLE
Create a script to convert translations from Google Docs (CSV) to JSON

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#69]
Hey guys,

2 weeks ago we've started working on i18n of OptriSpace and almost ready to translate our UI to Spanish and Portuguese.

* [How English translation looks like in our repo as JSON file](https://github.com/optriment/optrispace-frontend-v2/blob/master/locales/en/common.json)
* [How Portuguese translation looks like on Google Docs](https://docs.google.com/spreadsheets/d/1wrW-70t3swMeRHON2q2qlZHpfwIh6Z1MQA8g0iuHyXs/edit?usp=sharing)

How this task could be implemented:

1. Export Portuguese translation from Google Docs as CSV and save it somewhere on your laptop or PC
2. Create a script (using JavaScript) which requires two environment variables (`SRC` and `DEST`)
3. Script should read a CSV file from `SRC` path, transform file to JSON and save it to `DEST`

Example of usage (`i18n-transform.js` is the name of your script regarding this task):

```bash
SRC=./tmp/i18n/portuguese.csv DST=./locales/pt/common.json node ./scripts/i18n-transform.js
```

How it should work:
1. Script reads CSV line-by-line
2. Gets the key from a first column (e.g. `errors.messages.empty` from Portuguese file)
<img width="1213" alt="Captura de Tela 2023-04-04 às 2 24 50 PM" src="https://user-images.githubusercontent.com/335095/229764435-68dec2f3-4615-4ba0-8b50-e832dd611274.png">

3. Script splits this key into this one: https://github.com/optriment/optrispace-frontend-v2/blob/master/locales/en/common.json#L34 and uses translation (from a last column) as it is
4. Script keeps doing the same steps until end of file reached

If you have any questions, feel free to ask!

**Comment by Aatyagi** [comment]
@gruz0 would be happy to work on it . When do you want it ?

**Comment by gruz0** [comment]
@Aatyagi, hi! Thanks for your help and interest in our project!

We don't have any deadlines. Feel free to ask anything about this task, I am ready to help you!

**Comment by Aatyagi** [comment]
@gruz0, hey, thanks for the offered help, I am going to try to give the work by tomorrow otherwise by day after tomorrow latest .

**Comment by gruz0** [comment]
Hey @Aatyagi,

How is it going? Do you need any help?

**Comment by Aatyagi** [comment]
Hey , sorry friend i got busy with my university deadline . Will start working on it by tomorrow
