### ISSUE TITLE
Add a message that a customer will not be able to change a value of a contract

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#70]
In the interface for creating a contract we would like to have a message that the customer will not be able to change the cost of the contract after it has been created and double-check that customer has agreed on the cost with a contractor before creating the contract.

I suggest to use existing component: https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ConfirmationMessage/index.jsx

How this component is used: https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ContractCardForCustomer/index.jsx#L238

How this task can be implemented:
1. Customer opens an interface to create a new contract for a contractor
2. If all UI validations passed, "Add New" button will be enabled (it is already implemented)
3. Click on this button opens a confirmation dialog with hardcoded description
4. Customer should pick between two buttons: to decline this dialog or confirm a creation of the contract

**Comment by Aditya-A-G** [comment]
Hi @gruz0 
I would like to work on this issue

**Comment by gruz0** [comment]
@Aditya-A-G, do you have any questions about this task?
I would like to help you :-)

**Comment by Aditya-A-G** [comment]
Thank you for your prompt response, @gruz0. I will let you know if I have any questions as I start working on this issue.
