### ISSUE TITLE
Add a link to a job to a Contract Card

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend-v2#74]
This feature could help customers and freelancers jump to the original job which is related to the contract.

In this task we want to update two sidebars:

1. [src/components/ContractCardForCustomer/Sidebar.jsx](https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ContractCardForCustomer/Sidebar.jsx)
2. [src/components/ContractCardForContractor/Sidebar.jsx](https://github.com/optriment/optrispace-frontend-v2/blob/master/src/components/ContractCardForContractor/Sidebar.jsx)

Both sidebars have `contract` object in props with `jobAddress` property, which can be used to add a new list item to a specific sidebar. Link href should locate to `/jobs/${contract.jobAddress}`.

Contract sidebar looks like this:

<img width="434" alt="Captura de Tela 2023-04-05 às 2 04 54 PM" src="https://user-images.githubusercontent.com/335095/230051489-16580313-c2b5-4367-8667-9c0b8fc6ad67.png">

It would be great to add a new item after "Open the contractor's profile" item.

**Comment by paragborkar** [comment]
I Want To Change The Link To /jobs/${contract.jobAddress}

**Comment by Aditya-A-G** [comment]
Hi @gruz0 
I would like to work on this issue

**Comment by gruz0** [comment]
Hi @Aditya-A-G! Sure!

Nice to see you! 🤝

**Comment by gruz0** [comment]
@Aditya-A-G, please don't forget to pull changes from `master` branch :-)

**Comment by Aditya-A-G** [comment]
@gruz0  yes

**Comment by Aditya-A-G** [comment]
@gruz0 can you please review this pr #78

**Comment by gruz0** [comment]
Great! PR has been merged 🕺
